
# Get the measures from the server
GET http://localhost:3000/api/measures

###

# Add a new measure
POST http://localhost:3000/api/measures
Content-Type: application/json

{
  "type": 1,
  "image" : "",
  "value": 1
}

###

# Modify an existing measure
PUT http://localhost:3000/api/measures/1
Content-Type: application/json

{
  "value": 2
}

###

# Delete an existing measure
DELETE http://localhost:3000/api/measures/1

###
