
# Get the measurements from the server
GET http://localhost:3000/api/measurements

###

# Get the measurements by type
GET http://localhost:3000/api/measurements?type=weight

###

# Add a new measurement
POST http://localhost:3000/api/measurements
Content-Type: application/json

{
  "type": "weight",
  "image" : "",
  "value": 1
}

###

# Modify an existing measurement
PUT http://localhost:3000/api/measurements/1
Content-Type: application/json

{
  "value": 2
}

###

# Delete an existing measurement
DELETE http://localhost:3000/api/measurements/1

###
